books/urls.py
from django.urls import path
from . import views

app_name = 'books'
urlpatterns = [
    path('home/', views.home, name='home'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('', views.books, name='books'),
    path('get-books/', views.get_books, name='get-books'),
    path('toggle/', views.toggle, name='toggle'),
]

hello/urls.py
from django.urls import path
from . import views

app_name = 'hello'
urlpatterns = [
    path('', views.index, name='index'),
    path('add-status/', views.add_status, name='add-status'),
    path('profile/', views.profile, name='profile'),
]

lab_ppw_baru/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('hello.urls')),
    path('books/', include('books.urls')),
    path('subscribe/', include('subscribe.urls')),
    path('admin/', admin.site.urls),
]

subscribe/urls.py
from django.urls import path
from . import views

app_name = 'subscribe'
urlpatterns = [
    path('', views.subscribe, name='subscribe'),
    path('create-subscriber/', views.create_subscriber, name='create-subscriber'),
    path('form-check/', views.form_check, name='form-check'),
    path('subscribers-list/', views.subscribers_list, name='subscribers-list'),
    path('subscribers-list/get-subscribers/', views.get_subscriber, name='get-subscribers'),
    path('subscribers-list/unsubscribe/', views.unsubscribe, name='unsubscribe'),
]

hello/models.py
from django.db import models
from django.utils import timezone

class Status(models.Model):
    text = models.CharField(max_length=300)
    time = models.TimeField(default=timezone.localtime(timezone.now()))

    class Meta:
        verbose_name_plural = "statuses"

    def __str__(self):
        return self.text

hello/forms.py
from django import forms
from .models import Status

class StatusForm(forms.ModelForm):
    text = forms.CharField(widget=forms.TextInput(attrs={
        'class'         : 'form-control',
        'required'      : True,
        'placeholder'   : 'Kabar saya...'
    }), max_length=300)

    class Meta:
        model = Status
        fields = ('text',)

hello/views.py
from django import forms
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from .forms import StatusForm
from .models import Status

def index(request):
    status_form = StatusForm()
    statuses = Status.objects.all()
    context = {'status_form' : status_form, 'statuses': statuses}
    return render(request, 'hello/index.html', context)

def add_status(request):
    status_form = StatusForm(request.POST)
    if request.method == 'POST' and status_form.is_valid():
        Status.objects.create(text=status_form.cleaned_data.get('text'))
    return HttpResponseRedirect(reverse('hello:index'))

def profile(request):
    return render(request, 'hello/profile.html', {})

hello/templates/hello/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="William Gates">
        <meta name="google-signin-client_id" content="958782081053-pg3bg2ul602qnvcgifunl88omhspbh4c.apps.googleusercontent.com">

        <title>{% block title %}{% endblock %}</title>
        
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css" />
        <link rel="stylesheet" href="{% static 'css/fakeLoader.css' %}" type="text/css" />
        <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" />
        <link id="current-theme" rel="stylesheet" href="{% static 'css/dark_theme.css' %}" type="text/css" />
        
        <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/typed.min.js' %}"></script>
        <script src="{% static 'js/fakeLoader.min.js' %}"></script>
        <script src="https://apis.google.com/js/platform.js" async defer></script>
    </head>
    <body>
        <div id="fakeloader"></div>

        {% include 'hello/navbar.html' %}
        {% block content %}
        {% endblock %}

        <script type="text/javascript">
            var currentTheme = "dark";

            document.getElementById("theme").onclick = function () {
                if (currentTheme == "dark") {
                    document.getElementById("current-theme").href = "{% static 'css/light_theme.css' %}";
                    document.getElementById("navbar").classList.add("navbar-light");
                    document.getElementById("navbar").classList.add("bg-light");
                    document.getElementById("navbar").classList.remove("navbar-dark");
                    document.getElementById("navbar").classList.remove("bg-dark");
                    currentTheme = "light";
                }
                else if (currentTheme == "light") {
                    document.getElementById("current-theme").href = "{% static 'css/dark_theme.css' %}";
                    document.getElementById("navbar").classList.add("navbar-dark");
                    document.getElementById("navbar").classList.add("bg-dark");
                    document.getElementById("navbar").classList.remove("navbar-light");
                    document.getElementById("navbar").classList.remove("bg-light");
                    currentTheme = "dark";
                }
            };
        </script>

        <script>
            var acc = document.getElementsByClassName("accordion");
            var i;
            
            for (i = 0; i < acc.length; i++) {
                acc[i].addEventListener("click", function() {
                    this.classList.toggle("active");
                    var panel = this.nextElementSibling;
                    if (panel.style.display === "block") {
                        panel.style.display = "none";
                    } else {
                        panel.style.display = "block";
                    }
                });
            }
        </script>

        <script type="text/javascript">
            $("#fakeloader").fakeLoader();
        </script>

        <script type="text/javascript">
            $("#fakeloader").fakeLoader({
                timeToHide: 500,
                zIndex: "999",
                spinner: "spinner2",
                bgColor: "#000000"
            });
        </script>
    </body>
</html>

hello/templates/hello/index.html
{% extends "hello/base.html" %}
{% load static %}

{% block title %}Homepage{% endblock %}

{% block content %}
<div class="content text-center">
    <div class="container">
        <h1>Hello apa kabar?</h1>
        <form class="status-form" action="{% url 'hello:add-status' %}" method="POST">
            {% csrf_token %}
            {% for field in status_form.visible_fields %}
                <div class="form-group">
                    {{ field }}
                </div>
            {% endfor %}
            <button id="submit" class="btn btn-light" type="submit" value="Create Status">Tambahkan</button>
        </form>
    </div>

    <div class="container">
        <div class="row">
            {% for status in statuses %}
                <div class="card">
                    <div class="card-body align-items-center d-flex justify-content-center">
                        <p class="card-text">
                            Waktu pengisian: {{ status.time }}<br /><br />
                            {{ status.text }}
                        </p>
                    </div>
                </div>
            {% empty %}
                <div class="card">
                    <div class="card-body align-items-center d-flex justify-content-center">
                        <p class="card-text">
                            Kosong
                        </p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}

hello/templates/hello/navbar.html
<nav id="navbar" class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'hello:index' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'hello:profile' %}">Profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'books:books' %}">Books</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'subscribe:subscribe' %}">Subscribe</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'subscribe:subscribers-list' %}">Subscribers List</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'books:login' %}">Sign in</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'books:home' %}">Login Information</a>
            </li>
        </ul>
        <button id="theme" class="btn btn-outline-secondary my-2 my-sm-0 my-lg-0" type="submit">Change theme</button>
    </div>
</nav>

hello/templates/hello/profile.html
{% extends "hello/base.html" %}
{% load static %}

{% block title %}Profile{% endblock %}

{% block content %}
<div class="content text-center">
    <div class="container">
        <h1>Profil Saya</h1>
        <img id="profile-picture" src="https://dl.dropbox.com/s/3fyb4zwg0tzy7g8/picture.jpg?dl=0" alt="Self picture" />
        <h2>&gt; <span id="information"></span></h2><br />
        <p>Hai! Perkenalkan nama saya William Gates. Saya adalah mahasiswa jurusan Ilmu Komputer Universitas Indonesia angkatan 2017. Saya lahir di Rantauprapat pada tanggal 31 Juli 1999. Hobi saya adalah browsing dan bermain game. Sebelumnya, saya bersekolah di SMA Swasta Buddhis Jayanti. Salah satu alasan saya memilih jurusan Ilmu Komputer adalah karena saya tertarik dengan hal-hal yang berhubungan dengan teknologi. Selain itu, saya juga berharap agar saya bisa bekerja di perusahaan IT nantinya dan membangun startup sendiri.</p>
    </div>

    <div class="container" style="width: 50vw;">
        <button class="accordion">Pendidikan</button>
        <div class="panel">
            <p>(2017 - sekarang) Pendidikan Jenjang Sarjana<br />Universitas Indonesia</p>
        </div>

        <button class="accordion">Organisasi</button>
        <div class="panel">
            <p>(Januari 2018 - sekarang) KMBUI<br />Staf Departemen Website</p>
            <p>(Februari 2018 - sekarang) BEM Fasilkom UI<br />Staf Biro Pengembangan Teknologi Informasi</p>
            <p>(Maret 2018 - sekarang) Ristek Fasilkom UI<br />Junior member SIG Embedded System</p>
        </div>

        <button class="accordion">Prestasi</button>
        <div class="panel">
            <p>(2015) OSN Tingkat Kabupaten<br />Peringkat 1 bidang Informatika/Komputer</p>
            <p>(2015) FLS2N Tingkat Kabupaten<br />Peringkat 1 bidang Desain Poster</p>
            <p>(2016) OSN Tingkat Kabupaten<br />Peringkat 1 bidang Informatika/Komputer</p>
            <p>(2018) Gemastik 11<br />Peringkat 2 bidang Piranti Cerdas, Sistem Benam, dan IoT</p>
        </div>
    </div>

    <script type="text/javascript">
        var typed = new Typed("#information", {
            strings: ["NAMA^500 - WILLIAM GATES",
                      "NPM^500 - 1706040044"],
            typeSpeed: 40,
            loop: true
        });
    </script>

    <script>
        // (function(){
        //     $.getJSON("http://127.0.0.1:8000/static/js/data.json", function(result){
        //         $.each(result, function(i, field){
        //             $("#organization").append(field.name + "<br />");
        //         });
        //     });
        // })();
        (function() {
            $.ajax({
                type: "json",
                method: "GET",
                url: "http://127.0.0.1:8000/static/js/data.json",
                success: function(data) {
                    for (var i = 0; i < data.length; ++i) {
                        $("#organization").append(data[i].name + "<br />");
                    }
                }
            });
        })();
    </script>
</div>
{% endblock %}